apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-state-metrics
  name: kube-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-state-metrics
  strategy: {}
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      containers:
      - image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.19.0
        name: kube-state-metrics
        resources: {}
status: {}
