apiVersion: v1
kind: Service
metadata:
  labels:
    app: exporter-service
  name: exporter-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
spec:
  ports:
  - name: metrics 
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: node-exporter
  clusterIP: None
