apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: observability-quota
  namespace: observability
spec:
  hard:
    cpu: "10"
    memory: 4Gi
    persistentvolumeclaims: "10"
    pods: "20"
    replicationcontrollers: "10"
    resourcequotas: "1"
    secrets: "7"
    services: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: observability-limit
  namespace: observability
spec:
  limits:
    - type: Container
      default:
        cpu: 256m
        memory: 256Mi
      defaultRequest:
        cpu: 30m
        memory: 50Mi
      min:
        cpu: 30m
        memory: 50Mi
      max:
        cpu: 512m
        memory: 512Mi

